#pragma config(Sensor, in1,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroPID.c"

void configGyroPID(){
	gyroPID.port = in1;
	gyroPID.rightMasterMotor = port1;
	gyroPID.leftMasterMotor = port10;
	gyroPID.absoluteTolerance = 10.0;
	gyroPID.inputRangeMax = 3600.0; //the gyro sensor has values from -3600 to 3600
	gyroPID.inputRangeMin = -3600.0;
	gyroPID.outputRangeMax = 127.0; // motor value range
	gyroPID.outputRangeMin = -127.0;
}

task main()
{
	configGyroPID();
	initGyroPID(); // start the PID task
	gyroPID.setPoint = 450.0; // set desired target angle
	startGyroPID();
}
